### ISSUE TITLE
Shouldn't the values be declared in a .cpp file?

### ISSUE THREAD

**Issue by eliud892** [chuyangliu/snake#17]
I got 79 errors most of them are related to this problem, "only static const integral data members can be initialized within a class". Shouldn't the values of a class be declared in a .cpp file?
![screesht](https://user-images.githubusercontent.com/30704559/28942459-05ee1e9e-7861-11e7-85ba-85bb06ff47d0.png)

**Comment by chynl** [comment]
It's a new feature in C++11. Try to build the project using Visual Studio 2013 or higher version.
