### ISSUE TITLE
After DQN training, how to use trained model?

### ISSUE THREAD

**Issue by zinwalin** [chuyangliu/snake#34]
![image](https://user-images.githubusercontent.com/5416196/69627636-e70e0b80-10af-11ea-991f-9150193ed373.png)

**Comment by chynl** [comment]
[self._FREQ_SAVE](https://github.com/chuyangliu/snake/blob/master/snake/solver/dqn/__init__.py#L71) controls the frequency to save model parameters during training. Here the value is 20000, which means that model parameters will be saved every 20000 learning steps.

Saved model parameters are represented by three files under directory `logs`: `solver-net-<steps>.data-00000-of-00001`, `solver-net-<steps>.index`, and `solver-var-<steps>.json`. To use a trained model, modify [self._RESTORE_STEP](https://github.com/chuyangliu/snake/blob/master/snake/solver/dqn/__init__.py#L38) to the steps you want to use.

For example, if you want to use the model trained with 100000 learning steps. Ensure the three files `solver-net-100000.data-00000-of-00001`, `solver-net-100000.index`, and `solver-var-100000.json` are placed under directory `logs`. Then modify [self._RESTORE_STEP](https://github.com/chuyangliu/snake/blob/master/snake/solver/dqn/__init__.py#L38) to 100000. Now run the program with `python3 run.py -s dqn` and you are good to go!

**Comment by zinwalin** [comment]
to improve score, how to tweak parameters?

**Comment by chynl** [comment]
You can tune parameters in [this code region](https://github.com/chuyangliu/snake/blob/master/snake/solver/dqn/__init__.py#L31-L73) to improve score. I highly recommend going through the last four papers of the [references](https://github.com/chuyangliu/snake/blob/master/docs/algorithms.md) section to understand how these parameters affect the score.
