### ISSUE TITLE
39680 illegal hardware instruction macOS

### ISSUE THREAD

**Issue by JARVIS-AI** [chuyangliu/snake#46]
Everything is fine

- macOS : **10.14.6**
- CPU : **Intel Core i7**
- Ram : **8 GB**
- Python : **3.7.12**

Virtualenv installed, and all requirements installed (no error)

```python run.py``` give me : 
```py
[1]    39680 illegal hardware instruction  python run.py
```

**Comment by chynl** [comment]
No update on the issue since last year. Please reopen if issue still exists. Will help take a look.
